services:
  api:
    build: .
    container_name: wgg-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    depends_on:
      mysql:
        condition: service_healthy  # espera o MySQL estar saud√°vel
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=wggdb
      - DB_USER=root
      - DB_PASSWORD=password
    command: sh -c "pylint app/ || true && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: wgg-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wggdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql-data: